CREATE TABLE IF NOT EXISTS room (
  key TEXT NOT NULL PRIMARY KEY
) STRICT;

CREATE TABLE IF NOT EXISTS message (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  roomKey TEXT NOT NULL,
  request TEXT NOT NULL,
  responseStatus INTEGER NOT NULL,
  raw TEXT NOT NULL,
  FOREIGN KEY (roomKey) REFERENCES room(key) ON DELETE CASCADE
) STRICT;
